[[redirects]]
  from = "/api/*"
  to = "https://modern-ecommerce-fullstack.onrender.com/api/:splat"
  status = 200
  force = true
  
  [redirects.headers]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
  Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept, Origin"
  Access-Control-Allow-Credentials = "true"

[[headers]]
  for = "/*"
  
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
  Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept, Origin"
  Access-Control-Allow-Credentials = "true"

[build]
  command = "npm install && export NODE_OPTIONS=--max-old-space-size=4096 && CI=false npm run build"
  publish = "dist"