export { default as Dashboard } from './Dashboard'
export { default as AdminProducts } from './Products'
export { default as Users } from './Users'
export { default as Orders } from './Orders'
export { default as Settings } from './Settings' 